version: "3"

services:
  application:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command: yarn start
    labels:
	  - "traefik.enable=true"
	  # Change domain for the IP / domain
      - "traefik.frontend.rule=host:domain"

  reverse-proxy:
    image: traefik
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
